spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://m7915i.eos.grid.sina.com.cn:7915/kpi_dashboard?characterEncoding=utf-8&useSSL=false
    username: kpi_dashboard
    password: 4f3f05069f92049
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 10000
    minEvictableIdleTimeMillis: 19000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    numTestsPerEvictionRun: 25
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j

  redis:
    database: 3
    host: rm21330.eos.grid.sina.com.cn
    port: 21330
    password:
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    timeout: 0

swagger2:
  package: com.weibo.bop.pulse.query.controller
  enable: false

config:
  url: http://10.41.14.21:8502/config/client

#sessionid 的key
sessionKey:
  jsessionid: JSESSIONID
